server:
  port: 9090
spring:
# datasource properties
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:28762/railway
    username: postgres
    password: D1D44Gf3AffaDEbdGFDE36Cad-aeABDb
    driver-class-name: org.postgresql.Driver
# data jpa properties
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
# sending email properties
  mail:
    host: smtp.gmail.com
    port: 587
    username: elyorazimov098@gmail.com
    password: waldruhjxdqjvvri
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
# jwt token properties
jwt:
  expired: 90000000
  secret-key: lvNl4kXThUiIuXCoL1ticadNTD2qByyFIUMuz31F8wgydgwsbhjsbhjasbhjsbhjxbhjxvhsxvhjsvshvshvdghvdghdvgh
twilio:
  account_sid: AC4ffb1fd4a8be9fb6b02b769085b1cc54
  auth_token: af1235ac73489a1c91e750b952bbb052
  phone: +17174096109
springdoc:
  swagger-ui:
    path: /swagger-ui
